### ISSUE TITLE
Umfragenfeature: FAB überlappt mit Abstimmen/Ergebnisbutton

### ISSUE THREAD

**Issue by LCA311** [LCA311/leoapp-sources#17]
Lösung?

**Comment by MoritzLi** [comment]
Beim scrollen ausblenden
Nur beim Hochschulen und beim activitystart sichtbar

**Comment by LCA311** [comment]
Ist irgendwie suboptimal und nicht besonders Userfreundlich

**Comment by MoritzLi** [comment]
ist aber immer so also bei jeder app

**Comment by MoritzLi** [comment]
vorläufig gelöst (vielleicht noch andere Idee)
