### ISSUE TITLE
EssensQR Anmeldung

### ISSUE THREAD

**Issue by MoritzLi** [LCA311/leoapp-sources#39]
Bitte nimm die aus den Einstellungen heraus. Das ist irgendwie komisch. Vor allem, wenn das in zwei Preferences ist.
Ich würde einfach einen Dialog machen, der kommt, wenn man die Funktion aufruft und noch nichts angegeben hat, oder die Anmeldung fehlschlägt.

**Comment by LCA311** [comment]
Fixed
