### ISSUE TITLE
Start-Struktur ändern

### ISSUE THREAD

**Issue by MoritzLi** [LCA311/leoapp-sources#56]
Update-Task in Utils anmelden,
MainActivity nur starten, wenn nötig (MensaMode),

**Comment by LCA311** [comment]
Wieso UpdateTask? Den kannst du eh nicht wiederverwenden

**Comment by LCA311** [comment]
Die MainActivity musst du immer starten, sonst geht die App zu, wenn du auf Zurück klickst und du kommst nie wieder aus dem Mensamode raus.
